#!/usr/bin/env bash
echo $SHELL
export DB_USER=$DB_USER
export DB_PASS=$DB_PASS
echo "Removing conflicting files..."
rm -rf bitpay-gravityforms-plugin
rm -rf vendor
rm -rf bin

if [ -e composer.lock ]
then
       echo "Running Composer update..."
       composer update --no-dev
else
       echo "Running Composer Install..."
       composer install --no-dev
fi

echo "Building BitPay Plugin Directory..."
mkdir bitpay-gravityforms-plugin
mkdir bitpay-gravityforms-plugin/lib
cp -vr src/* bitpay-gravityforms-plugin
cp -vr vendor/* bitpay-gravityforms-plugin/lib
cp LICENSE bitpay-gravityforms-plugin/
cp README.md bitpay-gravityforms-plugin/
cp CHANGELOG bitpay-gravityforms-plugin/
